import Foundation

@Observable
final class ConfigManager {
    static let shared = ConfigManager()

    // Non-sensitive config stored in UserDefaults
    var llmProvider: String {
        didSet { UserDefaults.standard.set(llmProvider, forKey: "llmProvider") }
    }
    var llmModel: String {
        didSet { UserDefaults.standard.set(llmModel, forKey: "llmModel") }
    }
    var llmApiUrl: String {
        didSet { UserDefaults.standard.set(llmApiUrl, forKey: "llmApiUrl") }
    }
    var hfOffline: Bool {
        didSet { UserDefaults.standard.set(hfOffline, forKey: "hfOffline") }
    }
    var transformersOffline: Bool {
        didSet { UserDefaults.standard.set(transformersOffline, forKey: "transformersOffline") }
    }

    // Sensitive keys stored in Keychain — loaded into memory on init
    var llmApiKey: String = ""
    var openaiApiKey: String = ""

    private init() {
        let defaults = UserDefaults.standard
        self.llmProvider = defaults.string(forKey: "llmProvider") ?? "GEMINI"
        self.llmModel = defaults.string(forKey: "llmModel") ?? "gemini-2.0-flash-lite"
        self.llmApiUrl = defaults.string(forKey: "llmApiUrl") ?? ""
        self.hfOffline = defaults.bool(forKey: "hfOffline")
        self.transformersOffline = defaults.bool(forKey: "transformersOffline")

        self.llmApiKey = KeychainHelper.read(key: "LLM_API_KEY") ?? ""
        self.openaiApiKey = KeychainHelper.read(key: "OPENAI_API_KEY") ?? ""
    }

    var isConfigured: Bool {
        !llmApiKey.isEmpty
    }

    var defaultModel: String {
        llmProvider == "GEMINI" ? "gemini-2.0-flash-lite" : "deepseek-chat"
    }

    var defaultApiUrl: String {
        "https://api.deepseek.com/v1/chat/completions"
    }

    /// Persists API keys to Keychain and writes the .env file for the Python pipeline.
    func save() throws {
        KeychainHelper.save(key: "LLM_API_KEY", value: llmApiKey)
        KeychainHelper.save(key: "OPENAI_API_KEY", value: openaiApiKey)
        try writeEnvFile()
    }

    /// Returns the directory where .env and app data live.
    private var appSupportDir: URL {
        let appSupport = FileManager.default.urls(
            for: .applicationSupportDirectory, in: .userDomainMask
        ).first!
        return appSupport.appendingPathComponent("Limrose")
    }

    /// Generates and writes the .env file to ~/Library/Application Support/Limrose/.env
    func writeEnvFile() throws {
        let dir = appSupportDir
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        let envPath = dir.appendingPathComponent(".env")

        let dataDirPath = UserDefaults.standard.string(forKey: "dataDirPath") ?? ""

        var lines: [String] = []
        lines.append("# Generated by Limrose.app — do not edit manually")
        lines.append("# Changes made here will be overwritten when you save settings in the app.")
        lines.append("")

        // LLM Configuration
        lines.append("# LLM Configuration")
        lines.append("LLM_PROVIDER=\(llmProvider)")
        lines.append("LLM_API_KEY=\(llmApiKey)")

        let model = llmModel.isEmpty ? defaultModel : llmModel
        lines.append("LLM_MODEL=\(model)")

        if llmProvider == "DEEPSEEK" {
            let url = llmApiUrl.isEmpty ? defaultApiUrl : llmApiUrl
            lines.append("LLM_API_URL=\(url)")
        }

        lines.append("")

        // Data directory
        if !dataDirPath.isEmpty {
            lines.append("# Data Directory")
            lines.append("LIMROSE_DATA_DIR=\(dataDirPath)")
            lines.append("")
        }

        // Offline mode
        lines.append("# Offline mode for Hugging Face models")
        lines.append("HF_HUB_OFFLINE=\(hfOffline ? "1" : "0")")
        lines.append("TRANSFORMERS_OFFLINE=\(transformersOffline ? "1" : "0")")

        // Optional keys
        if !openaiApiKey.isEmpty {
            lines.append("")
            lines.append("# OpenAI Configuration")
            lines.append("OPENAI_API_KEY=\(openaiApiKey)")
        }

        lines.append("")

        let content = lines.joined(separator: "\n")
        try content.write(to: envPath, atomically: true, encoding: .utf8)

        // Set file permissions to owner-only read/write (0600)
        try FileManager.default.setAttributes(
            [.posixPermissions: 0o600],
            ofItemAtPath: envPath.path
        )
    }
}
